### ISSUE TITLE
Include graph для дальнейшего анализа

### ISSUE THREAD

**Issue by missingdays** [OSLL/jenkins_job_builder_visualization#13]
Как и call graph, include graph должен хранить внутренний граф (сейчас граф сразу формируется в GraphViz).
Пофиксить баг, когда несколько одинаковых include создают несколько ребер в графе.

**Comment by missingdays** [comment]
Пулл реквест #27 фиксит этот issue. 

Include graph теперь хранит внутреннее представление графа подключений.
Это исправляет баг, когда между двумя файлами могло отображаться несколько одинаковых ребер.

### Steps to reproduce
1. Запустить тесты
```
./scripts/run_tests.sh
```
2. Посмотреть на файл `test/test_include_graph/test_data/example2-test.yml_include.svg`, убедиться, что в нем нету повторяющихся ребер.

**Comment by zmm** [comment]
Проверил PR - все ОК, нужно только поправить конфликты и смержить с мастером.

**Comment by missingdays** [comment]
Исправил конфликты  в #27, смерджил с integration.

**Comment by missingdays** [comment]
Смерджил #32 с master
