### ISSUE TITLE
Расширить вывод тестов

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#19]
Сейчас скрипт запуска тестов пишет только общие сведения

vood@vood-ThinkPad:~/ws/yaml-unfolding$ ./run_test.sh 
......
----------------------------------------------------------------------
Ran 6 tests in 1.694s

OK

Хочется видеть список тестов с отметками пройден/не пройден

**Comment by missingdays** [comment]
Пулл реквест #26 фиксит этот issue.

### Steps to reproduce
1. Из корня проекта исполняем команду
```
./scripts/run_unit_tests.sh
```
2. Смотрим на вывод тестов.
