### ISSUE TITLE
Отображение параметров вызова на графе вызовов

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#21]
- из какой секции был сделан вызов
- с какими параметрами
- same_node
....

**Comment by missingdays** [comment]
Отправил пулл реквест #34

Добавил флаг `--call-display` для переключения между режимами отображения информации о вызове.

### Steps to reproduce
1. Из папки `maxscale-jenkins-job` выполнить команду
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml --call-graph --yaml-root maxscale_jobs/ --call-display edge
```
Убедиться, что в файле `build_all.yaml_call.svg` вызов отображается как отдельный узел.

2. Выполнить команду
 ```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml --call-graph --yaml-root maxscale_jobs/ --call-display text
```

Убедиться, что вызов отображается как текст.

**Comment by missingdays** [comment]
Для отображения секции, откуда идет вызов, создан отдельный #38.

**Comment by missingdays** [comment]
Создал пулл реквест #40 

Добавил параметры для отображения на графе вызовов

### Steps to reproduce
1. Из папки `maxscale-jenkins-jobs` запустить
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml --yaml-root maxscale_jobs/ --call-graph --call-parameters same-node
```
Убедиться, что параметер `same-node` отображается

2. Запустить
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml --yaml-root maxscale_jobs/ --call-graph --call-parameters same-node node-parameters
```
Убедиться, что отображаются параметры `same-node` и `node-parameters`.
