### ISSUE TITLE
Интеграционные тесты и самодокументация

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#22]
Необходимо завести список команд для запуска утилиты из корня репозитория на различных графах.
Каждый вызов проверять на Exit_code
Ссылку на список дать в readme

**Comment by missingdays** [comment]
Пулл реквест #26 фиксит этот issue.

Добавил интеграционные тесты в скрипт `/scripts/run_integration_tests.sh`. Данные для тестирования выкачиваются в `/tmp/` при помощи скрипта `/scripts/download_maxscale_jobs.sh`. Так же в нем зафиксирован коммит, в который всегда будет сделан checkout, чтобы зафиксировать все тестовые данные.

### Steps to reproduce
1. Запустить из корня проекта
```
./scripts/run_tests.sh
```
2. Убедиться, что все тесты проходят без ошибок.
3. (optional) в `/tmp` должна появиться папка `maxscale-jenkins-jobs`, которая используется для интеграционных тестов. Запустить `./scripts/run_tests.sh` еще раз, чтобы убедиться, что тесты работают, даже если папка уже есть до их запуска.

**Comment by zmm** [comment]
Поправьте пожалуйста вывод интеграционных тестов по аналогии с юниттестами - хочется видеть:
- по каждому отдельному тесту Ок/Fail
- общую статистику в конце (сколько упало/сколько было всего)
- общий OK/Fail

**Comment by missingdays** [comment]
Отправил #33

1. По каждому тесту выводится OK/FAIL
2. В конце выводится общая статистика
3. В конце выводится OK/FAIL в зависимости от того, чему равен exit code всех тестов.
