### ISSUE TITLE
run_test.sh должен возращать exit_code != 0 если тесты упали

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#25]

**Comment by missingdays** [comment]
Пулл реквест #26 фиксит этот issue.

### Steps to reproduce
1. Добавляем неправильную команду в `integration_test_data/test_commands.txt`, например
```
main.py --files failed_file.yaml --call-graph --yaml-root maxscale_jobs/
```
2. Исполняем из корня директории
```
./scripts/run_tests.sh
```
Тесты должны упать с ошибкой.
3. Проверяем, что вернулся ненулевой код
```
echo $?
```
