### ISSUE TITLE
Дополнительный параметр вызова - секция, откуда идет вызов

### ISSUE THREAD

**Issue by missingdays** [OSLL/jenkins_job_builder_visualization#38]
Нужно различать вызовы из различных секций - publishers/builders/others. Для этого нужно

- [ ] реализовать отображение легенды всего графа
- [ ] реализовать для ребра вызова дополнительные параметры, в которые включить секцию, откуда был вызов.

От Марка требуется подробно указать, какие секции считать особенными, и что делать с вызовами, которые к этим секциям не относятся.

**Comment by zmm** [comment]
Секций всего две publishers и builders, если вы видите еще - напишите где и посмотрим вместе.
Отображение предлагаю регулировать цветом - publishers зеленые, builders синие.

**Comment by missingdays** [comment]
Например, здесь `https://github.com/mariadb-corporation/maxscale-jenkins-jobs/blob/master/maxscale_jobs/build_all.yaml` есть секция `wrappers`

**Comment by missingdays** [comment]
Создал pull request #42

1. Добавил отображение легенды, опцию `--legend` командной строки для ее отображения
2. Добавил цвет ребра в зависимости от того, из какой секции идет вызов. 
    1. `publishers` - зеленые
    2. `builders` - синие
    3. остальные - черные

### Steps to reproduce
1. Из папки `maxscale-jenkins-jobs` последней версии выполнить команду
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml maxscale_jobs/build_and_test.yaml --call-graph --yaml-root maxscale_jobs/ --legend
```

В файле `build_all.yaml_call.svg` должна отображаться легенда, ребра должны быть правильных цветов.
