### ISSUE TITLE
определение связей между job 

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#4]
Необходимо используя конфиг как заданную точку:
- полностью его размотать используя существующий код (его можно рефакторить)
- найти у нее все возможные связи (job вызывает другой job)
- идентифицировать конфиги, относящиеся к связанным job

Что искать:
- в секции builders - trigger-builds (https://github.com/mariadb-corporation/maxscale-jenkins-jobs/blob/master/maxscale_jobs/include/build_all/call_build.yaml)
- в секции publishers - trigger-builds (https://github.com/mariadb-corporation/maxscale-jenkins-jobs/blob/master/maxscale_jobs/include/call_destroy.yaml)

**Comment by missingdays** [comment]
Отправил реализацию алгоритма извелечения вызовов из job.
Из-за индексирования директории конфигов для поиска job'ов по имени скрипт работает на несколько секунд дольше.
Добавил простой тест test_call.yml
