### ISSUE TITLE
Нумерация вызовов job, вызванных из одной job

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#44]
Необходимо отображать внутри job ее номер (если вызовов больше одной).
Например на графе вызовов build_all, хорошо бы увидеть какие вызовы делаются первыми, а какие вторыми.

**Comment by missingdays** [comment]
Создал пулл-реквест #48 

1. Добавил отображение порядка вызовов через параметр `--call-parameters call-order`

### Steps to reproduce
1. Установить ruamel.yaml. Требуется для сохранения порядка вызвов, поскольку вызовы хранятся в словаре. Стандартный yaml загрузчик не сохраняет порядок, в котором перечислены вызовы.
```
pip install -r requirements.txt
```
2. Из папки `maxscale-jenkins-jobs` исполнить команду
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml --yaml-root maxscale_jobs/ --call-graph --call-parameters call-order
```
Убедиться, что в файле `build_all.yaml_call.svg` корректно отображается порядок вызовов.

**Comment by missingdays** [comment]
Существует баг, при котором номера вызовов отображаются не в правильном порядке.
Вызвано это тем, что при парсинге .yaml файла не учитывается порядок, в котором заданы секции `builders`, `publishers` и так далее.
Нужно разобраться, как заставить парсер учитывать этот порядок.

**Comment by missingdays** [comment]
Пофикшено.
Теперь при загрузке yaml все загружается в `OrderedDict` в том порядке, который задан в кофинге.
