### ISSUE TITLE
настройка порядка отображения графов

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#45]
необходима опция командной строки, чтобы мы могли отобразить граф либо сверху вниз, либо справа налево либо иным образом (для компактности).

**Comment by missingdays** [comment]
Отправил пулл реквест #46 

Добавил опцию `--rank-dir`, которая может принимать значения `left-right` для отображения слева-направо, и `up-down` для отображения сверху-вниз.

### Steps to reproduce
1. Из папки `maxscale-jenkins-jobs` запустить
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/build_all.yaml --yaml-root maxscale_jobs/ --call-graph --legend --rank-dir up-down
```
Убедиться, что в файле `build_all.yaml_call.svg` граф отображается сверху-вниз.
