### ISSUE TITLE
Большой интеграционный тест

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#50]
Запустить инструмент в обоих режимах на всех job из maxscale-jenkins-job

**Comment by missingdays** [comment]
Отправил pull request #51 

Добавил тест для всех файлов в директории `maxscale_jobs` для `include graph` и `call graph`.

### Steps to reproduce
1. Из папки `jenkins_job_builder_visualization` запустить команду
```
./scripts/run_tests.sh
```
Убедиться, что файлы `/tmp/maxscale-jenkins-jobs/all_files_include.svg` и `/tmp/maxscale-jenkins-jobs/all_files_call.svg`  отображаются корректно.

2. Для ручной проверки из папки `maxscale-jenkins-jobs` выполнить команду
```
../jenkins_job_builder_visualization/main.py --files maxscale_jobs/* --yaml-root maxscale_jobs/ --call-graph --include-graph --legend --name all_files
```

Убедиться, что файлы `all_files_include.svg` и `all_files_call.svg` отображаются корректно. Файлы получаются большими, поэтому лучше открывать из графическим редактором.
