### ISSUE TITLE
Экспорт содержимого builders: shell в отдельные файлы

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#54]
Проблема: очень много bash кода лежит в builders: shell и его, например, нельзя проверить синтаксическим анализатором или shellcheck
Задача: добавить режим, в котором для заданных job создаются папки, в которых лежит по файлу для каждого этапа builders: shell

**Comment by missingdays** [comment]
Отправил пулл-реквест #62

Добавил флаг `--export-shell`, при помощи которого можно выгрузить содержимое всех `shell:` в отдельную папку.

### Steps to reproduce
1. Из папки `maxscale-jenkins-jobs`  исполнить команду
```
../jenkins_job_builder_visualization/main.py --export-shell exported_shell/ --yaml-root maxscale_jobs/
```
Убедиться, что в папке `exported_shell` лежат все конфиги.
