### ISSUE TITLE
Сигнализация об ошибках в режиме анализа с помощью exit_code

### ISSUE THREAD

**Issue by zmm** [OSLL/jenkins_job_builder_visualization#58]
Если критерий анализа не выполнен, то необходимо вернуть Exit_code=1

**Comment by missingdays** [comment]
Если добавить это сейчас, интеграционные тесты будут падать, поскольку в репозитории `maxscale-jenkins-jobs` анализ показывает ошибки. Стоит либо исправить все эти ошибки (но тогда при добавлении нового анализа тесты опять будут падать, пока не будут исправлены все ошибки), либо пересмотреть работу самих тестов.

**Comment by missingdays** [comment]
Для интеграционных тестов для режима анализа решено создать отдельные конфиги в `integration_tests_data`.

**Comment by missingdays** [comment]
Отправил пулл-реквест #61

В случае, если одна из проверок анализа обнаружила ошибки, программа при выходе возвращает ненулевой код.

### Steps to reproduce
1. Из папки `maxscale-jenkins-jobs` запустить
```
../jenkins_job_builder_visualization/main.py --analysis parameters_present:same-node --synonyms {same-node, node-parameters} --yaml-root maxscale_jobs/
```
Убедиться, что 
```
echo $?
```
выводит ненулевой код.
