### ISSUE TITLE
Циклические зависимости в Include Graph

### ISSUE THREAD

**Issue by missingdays** [OSLL/jenkins_job_builder_visualization#66]
Добавить в анализ циклические зависимости в графе подключений.

**Comment by missingdays** [comment]
Отправил pull request #67 

Добавил обработку циклических зависимостей для проекта.

К сожалению, выполнить полноценный анализ проблематично из-за того, что для анализа требуется полностью распаршенный проект, что невозможно сделать, если существует циклическая зависимость.

Поэтому в случае циклической зависимости будет выбрасываться исключение.

### Steps to reproduce
1. Добавить циклическую зависимость. Например, в `maxscale_jobs/include/slave.yaml` добавить
```yaml
cycle: !include './maxscale_jobs/build.yaml'
```

2. Запустить любую задачу и убедиться, что будет выброшено исключение, в котором описан цикл.
```
../jenkins_job_builder_visualization/main.py --include-graph
```
```
Exception: Cyclic include found. maxscale_jobs/include/slave.yaml -> maxscale_jobs/build.yaml -> maxscale_jobs/include/slave.yaml
```

**Comment by zmm** [comment]
При запуске команды (циклическую зависимость не вносил) падает:

vood@vood-ThinkPad:~/ws/maxscale-jenkins-jobs$ ../jenkins_job_builder_visualization/main.py --include-graph

Traceback (most recent call last):
  File "../jenkins_job_builder_visualization/main.py", line 49, in <module>
    yaml_unfolder = YamlUnfolder(root=yaml_root, rank_dir=args.rank_dir)
  File "/home/vood/ws/jenkins_job_builder_visualization/job_visualization/yaml_unfolder.py", line 23, in __init__
    self.init_file_index()
  File "/home/vood/ws/jenkins_job_builder_visualization/job_visualization/yaml_unfolder.py", line 35, in init_file_index
    self.file_index.load_files(self.root)
  File "/home/vood/ws/jenkins_job_builder_visualization/job_visualization/file_index.py", line 49, in load_files
    for filename in os.listdir(path):
OSError: [Errno 2] No such file or directory: ''

**Comment by missingdays** [comment]
Забыл, что в команде нужно указать `--yaml-root maxscale_jobs`
